# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1reOSa81R8NsFR5S4WKmfsUPVY_WLSR5v
"""

!npx playwright install-deps

"""crawling"""

#@title Twitter Auth Tok
twitter_auth_token = '306ed17c1595657cf45ceb29017f93d30f9c35da' # change this auth token

## Tahap Crawling

import pandas

# Install required Python package
!pip install pandas

# Install Node.js (because tweet-harvest built using Node.js)
!sudo apt-get update
!sudo apt-get install -y ca-certificates curl gnupg
!sudo mkdir -p /etc/apt/keyrings
!curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

!NODE_MAJOR=20 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

!sudo apt-get update
!sudo apt-get install nodejs -y

# Install missing dependencies for playwright
!sudo apt-get install -y libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev

!node -v

# Crawl Data

filename = 'demo_mahasiswa.csv'
search_keyword = 'demo mahasiswa or aksi mahasiswa since:2026-04-10 until:2026-06-25 lang:id'
limit = 500

!npx -y tweet-harvest@2.7.1 -o "{filename}" -s "{search_keyword}" --tab "LATEST" -l {limit} --token {twitter_auth_token}

import pandas as pd

# Define filename within this cell
filename = 'demo_mahasiswa.csv'

# Specify the path to your CSV file
file_path = "/content/tweets-data/demo_mahasiswa.csv"

# Read the CSV file into a pandas DataFrame
df = pd.read_csv('/content/tweets-data/demo_mahasiswa.csv')

# Display the DataFrame
display(df)

# Cek jumlah data yang didapatkan

num_tweets = len(df)
print(f"Jumlah tweet dalam dataframe adalah {num_tweets}.")

import pandas as pd
import os

# Lokasi file hasil crawling
harvest_filepath = "demo_mahasiswa.csv"

if 'df_harvested' in locals():

    print("Displaying the first 5 rows of the harvested data:")
    display(df_harvested.head())
    print(f"Total tweets harvested: {len(df_harvested)}")

elif os.path.exists(harvest_filepath):

    df_harvested = pd.read_csv(harvest_filepath)

    print(f"Displaying the first 5 rows from '{harvest_filepath}'")
    display(df_harvested.head())
    print(f"Total tweets harvested: {len(df_harvested)}")

else:

    print(f"File tidak ditemukan: {harvest_filepath}")

import pandas as pd

# 1. Baca file CSV hasil crawling
df = pd.read_csv('/content/demo_mahasiswa.csv')

# 2. Cek jumlah data dan nama kolom
print("Jumlah tweet yang berhasil diambil:", len(df))
print("Kolom yang tersedia:", df.columns.tolist())

# 3. Tampilkan 5 data teratas
df[['created_at', 'username', 'full_text']].head()

import subprocess
import sys

# Install snscrape library
try:
    import snscrape
except ImportError:
    print("Installing snscrape...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "snscrape"]) # Use subprocess to install
    print("snscrape installed successfully.")

# Install pandas for data handling
try:
    import pandas as pd
except ImportError:
    print("Installing pandas...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "pandas"]) # Use subprocess to install
    print("pandas installed successfully.")

"""## preprocecing"""

import re
import os
import sys
import subprocess
import pandas as pd

try:
    from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
except ImportError:
    print("Installing Sastrawi...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "Sastrawi"])
    from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

file_path = "/content/demo_mahasiswa.csv"

if os.path.exists(file_path):
    df = pd.read_csv(file_path)
    print(f"✅ Data berhasil dimuat: {len(df)} tweet")
else:
    raise FileNotFoundError(f"File tidak ditemukan: {file_path}")

factory = StopWordRemoverFactory()
stopword_remover = factory.create_stop_word_remover()

def clean_text_processing(text):

    if pd.isna(text):
        return ""

    text = str(text).lower()


    text = re.sub(r"http\S+|www\S+", "", text)
    text = re.sub(r"@\w+", "", text)
    text = re.sub(r"#", "", text)
    text = re.sub(r"\brt\b", "", text)
    text = re.sub(r"\d+", "", text)
    text = re.sub(r"[^a-zA-Z\s]", " ", text)
    text = stopword_remover.remove(text)

    # Hapus spasi berlebih
    text = re.sub(r"\s+", " ", text).strip()

    return text


df["clean_text"] = df["full_text"].apply(clean_text_processing)

print("✅ Preprocessing selesai.")

display(df[["full_text", "clean_text"]].head())

print("\nJumlah data :", len(df))
print("\nKolom DataFrame:")
print(df.columns.tolist())

import pandas as pd
import os

# Assuming harvest_filepath and df_harvested are available from previous cells.
# If not, you can redefine harvest_filepath here if needed:
# harvest_filepath = os.path.join('tweets-data', 'demo_mahasiswa.csv')

if 'df_harvested' in locals():
    print(f"Displaying the first 5 rows of the harvested data:")
    display(df_harvested.head())
    print(f"Total tweets harvested: {len(df_harvested)}")
elif os.path.exists(harvest_filepath):
    df_harvested = pd.read_csv(harvest_filepath)
    print(f"Displaying the first 5 rows of the harvested data from '{harvest_filepath}':")
    display(df_harvested.head())
    print(f"Total tweets harvested: {len(df_harvested)}")
else:
    print(f"Error: The DataFrame 'df_harvested' is not available and the file '{harvest_filepath}' was not found.")

# 1. Pastikan paket Sastrawi & Swifter Terinstal
!pip install Sastrawi
!pip install swifter

import os
import re
import pandas as pd
import swifter
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

# 2. Loading Dataset Otomatis Ke Dalam Memori Aktif 'df'
jalur_file = '/content/tweets-data/demo_mahasiswa.csv'
if os.path.exists(jalur_file):
    df = pd.read_csv(jalur_file)
else:
    df = pd.read_csv('/content/demo_mahasiswa.csv')

# 3. Pengaman Preprocessing: Memastikan kolom teks bersih sudah siap
def clean_tweet_simple(text):
    if pd.isna(text): return ""
    text = str(text).lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"[^a-zA-Z0-9\s@]", "", text)
    return text

# Membuat kolom 'processed_text' dan memecahnya menjadi list kata (token)
df['processed_text'] = df['full_text'].apply(clean_tweet_simple)
df['tweet_normalized'] = df['processed_text'].apply(lambda x: str(x).split())

# 4. Inisialisasi Stemmer dari Sastrawi
factory = StemmerFactory()
stemmer = factory.create_stemmer()

def stemmed_wrapper(term):
    return stemmer.stem(term)

# 5. Membangun Kamus Kata Unik (Term Dictionary) untuk Menghemat Komputasi
term_dict = {}

for document in df['tweet_normalized']:
    for term in document:
        if term not in term_dict:
            term_dict[term] = ' '

print(f"Jumlah kata unik terdeteksi: {len(term_dict)}")
print("------------------------")

# Proses stemming kata unik baris demi baris
for term in term_dict:
    term_dict[term] = stemmed_wrapper(term)
    print(term, ":" , term_dict[term])

print("\nHasil Akhir Kamus Stemming:")
print(term_dict)
print("------------------------")

# 6. Menerapkan Kamus Kata Dasar ke Dataframe Menggunakan SWIFTER (Multiprocessing)
def get_stemmed_term(document):
    return [term_dict[term] for term in document]

# Swifter secara otomatis mempercepat proses pemetaan teks dalam jumlah besar
df['tweet_tokens_stemmed'] = df['tweet_normalized'].swifter.apply(get_stemmed_term)

print("\nHasil DataFrame Kolom Baru ('tweet_tokens_stemmed'):")
print(df['tweet_tokens_stemmed'])

"""Sentence-Bert & Kmean"""

from sentence_transformers import SentenceTransformer
import pandas as pd # Import pandas if not already imported

# Ensure df is defined, otherwise load it
try:
    df
except NameError:
    print("DataFrame 'df' belum didefinisikan. Memuat dari CSV...")
    file_path_df = "/content/tweets-data/demo_mahasiswa.csv" # Adjust path if needed
    try:
        df = pd.read_csv(file_path_df)
        print(f"DataFrame 'df' berhasil dimuat dari {file_path_df}")
    except FileNotFoundError:
        raise FileNotFoundError(f"File '{file_path_df}' tidak ditemukan. Mohon jalankan sel crawling data atau preprocessing terlebih dahulu.")

# Load model Sentence-BERT
model = SentenceTransformer("all-MiniLM-L6-v2")

# Membuat embedding dari hasil preprocessing, menggunakan 'df' bukan 'df_harvested'
embeddings = model.encode(
    df["full_text"].fillna("").astype(str).tolist(), # Changed df_harvested to df
    show_progress_bar=True,
    convert_to_numpy=True
)
print("Embedding berhasil dibuat!")
print("Ukuran embedding:", embeddings.shape)

print(df.columns.tolist())

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.cluster import KMeans
from sklearn.feature_extraction.text import TfidfVectorizer

# =====================================================
# Validasi DataFrame
# =====================================================
try:
    df
except NameError:
    raise ValueError(
        "DataFrame 'df' belum dibuat. Jalankan terlebih dahulu proses Load Data (pd.read_csv)."
    )

# =====================================================
# Validasi Embedding SBERT
# =====================================================
try:
    embeddings
except NameError:
    raise ValueError(
        "Variabel 'embeddings' belum tersedia. Jalankan terlebih dahulu proses SBERT Embedding."
    )

# =====================================================
# Menentukan kolom teks
# =====================================================
if "clean_text" in df.columns:
    text_column = "clean_text"
elif "processed_text" in df.columns:
    text_column = "processed_text"
elif "full_text" in df.columns:
    text_column = "full_text"
else:
    raise ValueError(
        "Kolom teks tidak ditemukan. Pastikan terdapat salah satu kolom: clean_text, processed_text, atau full_text."
    )

print(f"Menggunakan kolom: {text_column}")

# =====================================================
# KMeans Clustering
# =====================================================
kmeans = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=10
)

df["cluster_label"] = kmeans.fit_predict(embeddings)

# =====================================================
# Menggabungkan dokumen tiap cluster
# =====================================================
cluster_docs = (
    df.groupby("cluster_label")[text_column]
      .apply(lambda x: " ".join(x.astype(str)))
      .reset_index(name="cluster_text")
)

# =====================================================
# TF-IDF Keyword Extraction
# =====================================================
tfidf_vectorizer = TfidfVectorizer(
    ngram_range=(1, 2),
    max_features=1000,
    stop_words=None
)

tfidf_matrix = tfidf_vectorizer.fit_transform(cluster_docs["cluster_text"])

fitur_kata = np.array(tfidf_vectorizer.get_feature_names_out())

nama_tema_ilmiah = {
    0: "Isu Finansial & Komersialisasi Pendidikan",
    1: "Kritik Kebijakan Negara & Gerakan Politik",
    2: "Kebebasan Berpendapat & Tindakan Represif"
}

print("=" * 80)
print("HASIL EKSTRAKSI TEMA")
print("=" * 80)

for idx, row in cluster_docs.iterrows():

    skor = tfidf_matrix[idx].toarray().flatten()
    urutan = skor.argsort()[::-1]

    keywords = []

    for i in urutan:
        kata = fitur_kata[i]

        if kata.startswith("@"):
            continue

        if kata not in keywords:
            keywords.append(kata)

        if len(keywords) == 5:
            break

    print(f"\n📌 Cluster {row['cluster_label']}")
    print(f"Tema     : {nama_tema_ilmiah.get(row['cluster_label'], 'Tema Lain')}")
    print(f"Keyword  : {', '.join(keywords)}")

# =====================================================
# Visualisasi Distribusi Cluster
# =====================================================
hitung_tema = (
    df["cluster_label"]
      .value_counts()
      .sort_index()
)

label = [
    "Isu Finansial\n& UKT",
    "Kritik Kebijakan\n& Gerakan",
    "Kebebasan\nBerpendapat"
]

plt.figure(figsize=(10,6))
sns.set_theme(style="whitegrid")

ax = sns.barplot(
    x=label,
    y=hitung_tema.values,
    hue=label,
    palette="Blues_d",
    legend=False
)

for p in ax.patches:
    ax.annotate(
        f"{int(p.get_height())}",
        (
            p.get_x() + p.get_width()/2,
            p.get_height()
        ),
        ha="center",
        va="bottom",
        xytext=(0,5),
        textcoords="offset points"
    )

plt.title("Distribusi Tema Tweet", fontsize=14)
plt.xlabel("Tema")
plt.ylabel("Jumlah Tweet")
plt.tight_layout()
plt.show()

"""Social Network Analysis (SNA) & Community Detection"""

!pip install networkx python-louvain

import re
import networkx as nx
import matplotlib.pyplot as plt
import community.community_louvain as community_louvain

# Membuat graph kosong
G = nx.Graph()

# Fungsi mengambil mention (@username)
def extract_mentions(text):
    if pd.isna(text):
        return []
    return re.findall(r'@(\w+)', str(text))

# Membuat edge antar akun
for _, row in df.iterrows():

    source = row["username"]

    mentions = extract_mentions(row["full_text"])

    for target in mentions:

        if source != target:

            if G.has_edge(source, target):
                G[source][target]["weight"] += 1
            else:
                G.add_edge(source, target, weight=1)

print("="*60)
print("HASIL SOCIAL NETWORK")
print("="*60)

print("Jumlah Node :", G.number_of_nodes())
print("Jumlah Edge :", G.number_of_edges())

degree = nx.degree_centrality(G)
betweenness = nx.betweenness_centrality(G)
closeness = nx.closeness_centrality(G)

import pandas as pd

centrality_df = pd.DataFrame({

    "Username": list(degree.keys()),
    "Degree": list(degree.values()),
    "Betweenness": [betweenness[x] for x in degree.keys()],
    "Closeness": [closeness[x] for x in degree.keys()]

})

centrality_df = centrality_df.sort_values(
    by="Degree",
    ascending=False
)

print(centrality_df.head(10))

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA # atau dari sklearn.manifold import TSNE

# 1. Asumsikan 'embeddings' adalah hasil dari model.encode(df['clean_text'])
# Kita reduksi dimensinya menjadi 2 komponen (X dan Y)
pca = PCA(n_components=2, random_state=42)
embeddings_2d = pca.fit_transform(embeddings)

# 2. Masukkan koordinat X dan Y ke dalam DataFrame agar mudah di-plot
df_harvested['X'] = embeddings_2d[:, 0]
df_harvested['Y'] = embeddings_2d[:, 1]

pip install adjustText

from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

# Menggunakan DataFrame `df` yang sudah diproses di sel-sel sebelumnya.
embeddings = model.encode(
   df["full_text"].fillna("").astype(str).tolist(),

    show_progress_bar=True,
    convert_to_numpy=True
)
print(df.columns.tolist())

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
import os

# ==========================================
# 1. Memuat Dataset (Dengan Fitur Upload Otomatis)
# ==========================================
file_path_df = "/content/demo_mahasiswa.csv"

# Cek apakah file sudah ada di Colab
if not os.path.exists(file_path_df):
    print("File tidak ditemukan di Colab. Memunculkan tombol upload...")
    from google.colab import files
    # Ini akan memunculkan tombol "Choose Files" di bawah cell
    uploaded = files.upload()

    # Memastikan file yang diupload namanya benar
    if 'demo_mahasiswa.csv' not in uploaded:
        raise FileNotFoundError("Pastikan Anda mengunggah file dengan nama 'demo_mahasiswa.csv'")

# Membaca DataFrame
df = pd.read_csv(file_path_df)
print(f"DataFrame berhasil dimuat! Jumlah baris: {len(df)}")

# Pastikan tidak ada data teks yang kosong
df = df.dropna(subset=['full_text']).reset_index(drop=True)

# ==========================================
# (Lanjutkan ke Bagian 2 dan seterusnya di bawah sini...)
# ==========================================
# 2. Vektorisasi Teks dengan TF-IDF
vectorizer = TfidfVectorizer(max_features=2000)
X_tfidf = vectorizer.fit_transform(df['full_text'])

# ... (sisipkan sisa kode K-Means dan PCA Anda di sini)

import pandas as pd
import community.community_louvain as community_louvain
import networkx as nx
import re # Import 're' for regex operations

# Ensure 'G' (graph) is defined
try:
    G # Attempt to access G
except NameError:
    print("Variabel 'G' (graph) belum didefinisikan. Membuat ulang graph...")
    # Initialize G and extract mentions if G is not defined
    G = nx.Graph()

    # Function to extract mentions (@username)
    def extract_mentions(text):
        if pd.isna(text):
            return []
        return re.findall(r'@(\w+)', str(text))

    # Check if 'df' DataFrame is available before iterating
    try:
        df
    except NameError:
        raise NameError("DataFrame 'df' belum didefinisikan. Mohon jalankan sel yang membuat DataFrame terlebih dahulu.")

    # Membuat edge antar akun
    for _, row in df.iterrows():
        source = row["username"]
        mentions = extract_mentions(row["full_text"])
        for target in mentions:
            if source != target:
                if G.has_edge(source, target):
                    G[source][target]["weight"] += 1
                else:
                    G.add_edge(source, target, weight=1)
    print("Graph 'G' berhasil dibuat ulang.")


# Calculate the best partition if 'partition' is not already defined
try:
    partition
except NameError:
    partition = community_louvain.best_partition(G)
    print("Partitioning berhasil dilakukan.")

community_df = pd.DataFrame({
    "Username": list(partition.keys()),
    "Community": list(partition.values())
})

community_df = community_df.sort_values("Community")

display(community_df)

print("="*60)
print("NETWORK STATISTICS")
print("="*60)

print("Node               :", G.number_of_nodes())
print("Edge               :", G.number_of_edges())
print("Density            :", round(nx.density(G),4))
print("Average Degree     :", round(sum(dict(G.degree()).values())/G.number_of_nodes(),2))

partition

print(df.columns.tolist())

print(df.head())

from sentence_transformers import SentenceTransformer
import pandas as pd # Ensure pandas is imported

# Check if 'embeddings' is defined, if not, create it.
try:
    embeddings
except NameError:
    print("Variabel 'embeddings' belum didefinisikan. Membuat ulang...")

    # Ensure 'df' DataFrame is available. This logic is adapted from previous cells.
    try:
        df
    except NameError:
        print("DataFrame 'df' belum didefinisikan. Memuat dari CSV...")
        file_path_df = "/content/tweets-data/demo_mahasiswa.csv"
        try:
            df = pd.read_csv(file_path_df)
            print(f"DataFrame 'df' berhasil dimuat dari {file_path_df}")
        except FileNotFoundError:
            raise FileNotFoundError(f"File '{file_path_df}' tidak ditemukan. Mohon jalankan sel crawling data terlebih dahulu.")

    model = SentenceTransformer("all-MiniLM-L6-v2")
    embeddings = model.encode(
        df["full_text"].fillna("").astype(str).tolist(),
        show_progress_bar=True,
        convert_to_numpy=True
    )
    print("Embeddings berhasil dibuat ulang.")

print(type(embeddings))
print(embeddings.shape)

import pandas as pd
import community.community_louvain as community_louvain
import networkx as nx
import re

# Ensure 'df' DataFrame is available
try:
    df
except NameError:
    print("DataFrame 'df' belum didefinisikan. Memuat dari CSV...")
    file_path_df = "/content/tweets-data/demo_mahasiswa.csv"
    try:
        df = pd.read_csv(file_path_df)
        print(f"DataFrame 'df' berhasil dimuat dari {file_path_df}")
    except FileNotFoundError:
        raise FileNotFoundError(f"File '{file_path_df}' tidak ditemukan. Mohon jalankan sel crawling data terlebih dahulu.")

# Ensure 'G' (graph) is defined or re-defined here
# This logic is adapted from previous cells (e.g., 5SCrcJ6DxUDH, Z0PpfSSux0ai)
# to make this cell self-contained regarding the 'G' variable.

# Initialize G
G = nx.Graph()

# Function to extract mentions (@username)
def extract_mentions(text):
    if pd.isna(text):
        return []
    return re.findall(r'@(\w+)', str(text))

# Membuat edge antar akun
# 'df' is now guaranteed to be defined at this point.
for _, row in df.iterrows():
    source = row["username"]
    mentions = extract_mentions(row["full_text"])
    for target in mentions:
        if source != target:
            if G.has_edge(source, target):
                G[source][target]["weight"] += 1
            else:
                G.add_edge(source, target, weight=1)


# Mengambil hasil partisi (dictionary berupa {username: community_id})
partition = community_louvain.best_partition(G)

# ==========================================
# Nama Topik
# ==========================================
nama_topik = {
    0: "Isu Finansial & Komersialisasi Pendidikan",
    1: "Kritik Kebijakan Negara & Gerakan Politik",
    2: "Kebebasan Berpendapat & Tindakan Represif"
}

# ==========================================
# Memasukkan Community ke Dataframe Utama
# ==========================================
# Alih-alih membuat dataframe baru dan melakukan merge,
# kita bisa langsung me-mapping 'username' ke 'partition'
df["community"] = df["username"].map(partition)

# ==========================================
# Menambahkan Nama Topik
# ==========================================
df["topic"] = df["community"].map(nama_topik)

# ==========================================
# Tampilkan hasil
# ==========================================
display(df.head())

# Untuk memeriksa nilai community yang muncul:
print("Nilai unik di kolom 'community':", df["community"].unique().tolist())

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Ensure df is defined, otherwise load it (this assumes df is the primary DataFrame)
try:
    df
except NameError:
    print("DataFrame 'df' belum didefinisikan. Memuat dari CSV...")
    file_path_df = "/content/dataset_final_hasil_pipeline.csv" # Or 'demo_mahasiswa.csv'
    try:
        df = pd.read_csv(file_path_df)
        print(f"DataFrame 'df' berhasil dimuat dari {file_path_df}")
    except FileNotFoundError:
        raise FileNotFoundError(f"File '{file_path_df}' tidak ditemukan. Mohon jalankan sel sebelumnya untuk memuat data.")

# Menghitung jumlah tweet per topik
topic_distribution = df['topic'].value_counts().reset_index()
topic_distribution.columns = ['Topic', 'Count']

# Membuat bar plot untuk visualisasi distribusi topik
plt.figure(figsize=(10, 6))
sns.barplot(x='Topic', y='Count', data=topic_distribution, palette='viridis')
plt.title('Distribusi Topik Tweet', fontsize=16)
plt.xlabel('Topik', fontsize=12)
plt.ylabel('Jumlah Tweet', fontsize=12)
plt.xticks(rotation=45, ha='right') # Memutar label X agar tidak tumpang tindih
plt.tight_layout() # Menyesuaikan layout agar semua elemen terlihat
plt.show()

output_csv_path = '/content/dataset_final_hasil_pipeline.csv'
df.to_csv(output_csv_path, index=False)
print(f"Final DataFrame successfully saved to {output_csv_path}")

import networkx as nx
import pandas as pd

# 1. Export ke format GEXF (Format paling gampang untuk Gephi)
# Format ini otomatis menyimpan node, edge, dan weight-nya
nx.write_gexf(G, "/content/network_mahasiswa.gexf")
print("File GEXF berhasil dibuat! Silakan download dan buka di Gephi.")

# 2. ATAU, Export ke format CSV (Nodes dan Edges) jika butuh atribut lengkap
# Membuat Edges (Relasi)
edges_df = nx.to_pandas_edgelist(G)
edges_df.rename(columns={'source': 'Source', 'target': 'Target', 'weight': 'Weight'}, inplace=True)
edges_df.to_csv('/content/edges_gephi.csv', index=False)

# Membuat Nodes (Atribut Akun & Topiknya)
# Kita ambil dari dataframe 'df' yang sudah ada kolom 'topic' dan 'community'
nodes_df = df[['username', 'community', 'topic']].drop_duplicates(subset=['username'])
nodes_df.rename(columns={'username': 'Id'}, inplace=True)
nodes_df['Label'] = nodes_df['Id'] # Gephi butuh kolom Label

nodes_df.to_csv('/content/nodes_gephi.csv', index=False)
print("File edges_gephi.csv dan nodes_gephi.csv berhasil dibuat!")

# 1. Install library yang dibutuhkan untuk Algoritma Apriori
# !pip install mlxtend (Sudah terinstall, bisa di-skip)

import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.preprocessing import TransactionEncoder

print("Memulai proses Frequent Term-Based Clustering (FTC)...")

# 2. Deteksi otomatis nama kolom teks yang ada di dataset
if "tweet_normalized" in df.columns:
    kolom_teks = "tweet_normalized"
elif "clean_text" in df.columns:
    kolom_teks = "clean_text"
elif "processed_text" in df.columns:
    kolom_teks = "processed_text"
elif "full_text" in df.columns:
    kolom_teks = "full_text"
else:
    raise ValueError("❌ Kolom teks tidak ditemukan! Cek kembali nama kolom di datasetmu.")

print(f"✅ Menggunakan kolom teks: '{kolom_teks}'")

# 3. Siapkan Data Teks (Memecah kalimat menjadi token kata)
dataset_kata = [str(tweet).split() for tweet in df[kolom_teks].dropna()]

# 4. Transformasi Data (Format Apriori)
te = TransactionEncoder()
te_ary = te.fit(dataset_kata).transform(dataset_kata)
df_apriori = pd.DataFrame(te_ary, columns=te.columns_)

print("Mencari Frequent Itemsets (Kombinasi kata yang sering muncul bersamaan)...")

# 5. Inti FTC: Algoritma Apriori (min_support=0.03 artinya minimal 3%)
frequent_itemsets = apriori(df_apriori, min_support=0.03, use_colnames=True)

# 6. Merapikan Hasil
frequent_itemsets = frequent_itemsets.sort_values(by='support', ascending=False)
frequent_itemsets['jumlah_kata'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))

print("\n✅ Hasil Kandidat Klaster FTC:")
display(frequent_itemsets.head(20))

import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.preprocessing import TransactionEncoder

# =================================================================
# 1. PENANGKAL ERROR: MEMUAT ULANG DATAFRAME 'df' JIKA HILANG
# =================================================================
try:
    df
except NameError:
    print("DataFrame 'df' hilang dari memori Colab. Memuat ulang dari CSV...")
    # Pastikan nama file CSV ini sesuai dengan yang ada di panel folder sebelah kiri
    file_path = 'dataset_final_hasil_pipeline.csv'
    try:
        df = pd.read_csv(file_path)
        print("✅ Data 'df' berhasil dimuat kembali!")
    except FileNotFoundError:
        print(f"❌ ERROR: File {file_path} tidak ditemukan!")
        print("Solusi: Cek ikon folder di kiri, pastikan file CSV datamu ada di sana.")
        raise

# =================================================================
# 2. PROSES FTC (APRIORI)
# =================================================================
# Check if 'frequent_itemsets' and 'df_apriori' are defined. If not, re-generate them.
try:
    frequent_itemsets
    df_apriori
except NameError:
    print("Membangun ulang model Frequent Itemsets...")

    # Pastikan membuang data yang kosong/NaN agar split() tidak error
    dataset_kata = [str(tweet).split() for tweet in df['tweet_normalized'].dropna()]

    # Transformasi Data (Format Apriori)
    te = TransactionEncoder()
    te_ary = te.fit(dataset_kata).transform(dataset_kata)
    df_apriori = pd.DataFrame(te_ary, columns=te.columns_)

    # Inti FTC: Algoritma Apriori (min_support 0.03 = 3%)
    frequent_itemsets = apriori(df_apriori, min_support=0.03, use_colnames=True)

    # Merapikan Hasil
    frequent_itemsets = frequent_itemsets.sort_values(by='support', ascending=False)
    frequent_itemsets['jumlah_kata'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))
    print("✅ Variabel 'frequent_itemsets' dan 'df_apriori' berhasil dibangun ulang.")

# =================================================================
# 3. PENYUSUNAN FORMAT d1, d2, d3 DAN EKSPOR KE CSV
# =================================================================
# Ambil semua kandidat itemsets
ftc_kandidat = frequent_itemsets.copy().reset_index(drop=True)

# Fungsi Pelacak Dokumen (Tanpa batasan)
def cari_dokumen_lengkap(itemset, df_boolean):
    # Cari baris di mana SEMUA kata dalam kombinasi ini ada
    baris_cocok = df_boolean[list(itemset)].all(axis=1)

    # Ambil nomor indeks barisnya
    indeks_dokumen = df_boolean.index[baris_cocok].tolist()

    # Ubah format angkanya menjadi d1, d2, d3
    doc_ids = [f'd{i+1}' for i in indeks_dokumen]

    return '{' + ', '.join(doc_ids) + '}'

print("Sedang melacak dokumen untuk setiap klaster (proses ini mungkin butuh belasan detik)...")

# Terapkan pelacak dokumen ke data kita
ftc_kandidat['Documents'] = ftc_kandidat['itemsets'].apply(lambda x: cari_dokumen_lengkap(x, df_apriori))

# Format kolom 'Terms' agar menggunakan kurung kurawal
ftc_kandidat['Terms'] = ftc_kandidat['itemsets'].apply(lambda x: '{' + ', '.join(list(x)) + '}')

# Susun hasil akhirnya
tabel_mirip_slide = ftc_kandidat[['Terms', 'Documents']]

# Simpan ke CSV
jalur_simpan_csv = 'dataset_final_hasil_pipeline.csv'
tabel_mirip_slide.to_csv(jalur_simpan_csv, index=False)

print(f"✅ MANTAP! Data FTC berhasil diekspor dan disimpan ke: {jalur_simpan_csv}")
print("Silakan buka panel 'Files' (ikon folder) di sebelah kiri untuk men-download file CSV tersebut.")

import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.preprocessing import TransactionEncoder

print("=== MEMULAI PROSES FREQUENT TERM CLUSTERING (FTC) ===")

# 1. Pastikan DataFrame df sudah ada di memori
try:
    df
except NameError:
    raise ValueError("❌ DataFrame 'df' belum ada! Pastikan kamu sudah menjalankan pd.read_csv() di cell atas.")

# 2. Deteksi otomatis nama kolom teks di datasetmu
if "tweet_normalized" in df.columns:
    kolom_teks = "tweet_normalized"
elif "clean_text" in df.columns:
    kolom_teks = "clean_text"
elif "processed_text" in df.columns:
    kolom_teks = "processed_text"
elif "full_text" in df.columns:
    kolom_teks = "full_text"
else:
    raise ValueError("❌ Kolom teks tidak ditemukan! Cek kembali nama kolom di datasetmu.")

print(f"✅ Menggunakan kolom teks: '{kolom_teks}'")

# 3. Siapkan Data Teks
dataset_kata = [str(tweet).split() for tweet in df[kolom_teks].dropna()]

# 4. Transformasi Data untuk Apriori
te = TransactionEncoder()
te_ary = te.fit(dataset_kata).transform(dataset_kata)
df_apriori = pd.DataFrame(te_ary, columns=te.columns_)

print("⏳ Mencari kandidat klaster kata (Apriori)...")

# 5. Inti FTC: Algoritma Apriori
frequent_itemsets = apriori(df_apriori, min_support=0.03, use_colnames=True)
frequent_itemsets = frequent_itemsets.sort_values(by='support', ascending=False)
frequent_itemsets['jumlah_kata'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))

# 6. Membentuk Format {sun, fun} -> {d1, d2, d3}
ftc_kandidat = frequent_itemsets.copy().reset_index(drop=True)

def cari_dokumen_lengkap(itemset, df_boolean):
    baris_cocok = df_boolean[list(itemset)].all(axis=1)
    indeks_dokumen = df_boolean.index[baris_cocok].tolist()
    doc_ids = [f'd{i+1}' for i in indeks_dokumen]
    return '{' + ', '.join(doc_ids) + '}'

print("⏳ Melacak ID dokumen untuk setiap klaster (d1, d2, d3)...")
ftc_kandidat['Documents'] = ftc_kandidat['itemsets'].apply(lambda x: cari_dokumen_lengkap(x, df_apriori))
ftc_kandidat['Terms'] = ftc_kandidat['itemsets'].apply(lambda x: '{' + ', '.join(list(x)) + '}')

# Menyusun tabel akhir
tabel_mirip_slide = ftc_kandidat[['Terms', 'Documents']]

# 7. Tampilkan ke layar
print("\n=== HASIL DOCUMENT CLUSTERING FTC ===")
display(tabel_mirip_slide.head(20).style.hide(axis="index"))

# 8. Simpan ke CSV
jalur_simpan_csv = '/content/hasil_clustering_ftc.csv'
tabel_mirip_slide.to_csv(jalur_simpan_csv, index=False)
print(f"\n✅ MANTAP! File CSV berhasil disimpan di: {jalur_simpan_csv}")